### ISSUE TITLE
[FEAT] Mlflow tracking server

### ISSUE THREAD

**Issue by jihyun-0611** [boostcampaitech7/level2-objectdetection-cv-23#3]
### 📄 만들고자 하는 기능

mlflow를 활용해 중앙 tracking server를 만들고 해당 서버에 모든 실험 기록 
- 각자의 작업 서버 및 로컬에서 MLflow UI에 접근하여 실험 추적 결과를 확인할 수 있음 

### 🌱 구현 내용

- [x] torchvision baseline code에 mlflow model tracking 적용 
- [x] detectron2 baseline code에 mlflow model tracking 적용 
- [x] mmdetection baseline code에 mlflow model tracking 적용

### 📚 참고 자료

[https://mlflow.org/docs/latest/deep-learning/pytorch/guide/index.html](https://mlflow.org/docs/latest/deep-learning/pytorch/guide/index.html)
[https://philenius.github.io/machine%20learning/2022/01/09/how-to-log-artifacts-metrics-and-parameters-of-your-detectron2-model-training-to-mlflow.html](https://philenius.github.io/machine%20learning/2022/01/09/how-to-log-artifacts-metrics-and-parameters-of-your-detectron2-model-training-to-mlflow.html)
[https://mmcv.readthedocs.io/en/master/api.html#mmcv.runner.MlflowLoggerHook](url)
[https://mmcv.readthedocs.io/en/v1.3.14/_modules/mmcv/runner/hooks/logger/mlflow.html](url)
[https://pytorch.org/vision/0.12/generated/torchvision.models.detection.fasterrcnn_resnet50_fpn.html#torchvision.models.detection.fasterrcnn_resnet50_fpn](url)

### 📅 예상 기간

2024-10-04 ~ 2024-10-10
